Repository TeamStrata/strata, pull requests merged in 2025-05, with the labels that each got.

#39 Clean up Go code in ./pkg/
  pkg/api/queries.go
  pkg/api/routes.go
  pkg/database/database.go
Labels: go

#43 fix: update initial user in data.sql
  database/1_schema.sql
  database/2_data.sql
Labels: bug

#45 fix(#44): Docker container now starting strata
  Dockerfile
  README.md
Labels: bug, Ready to Merge!

#68 feat: We can now open the frontend page from the server hosted in docker.
  Dockerfile
  cmd/main.go
  compose.yml
Labels: go, docker

#67 Add DELETE user route
  cmd/main.go
  pkg/api/routes.go
  pkg/database/database.go
  pkg/test/database_test.go
Labels: go

#66 Add GET users route
  cmd/main.go
  pkg/api/routes.go
  pkg/database/database.go
  pkg/test/database_test.go
Labels: go

#73 Add user roles to backend
  cmd/main.go
  database/1_schema.sql
  database/2_data.sql
  pkg/api/routes.go
  pkg/database/database.go
  pkg/test/database_test.go
Labels: go

#85 Add routes for roles
  .env.actions
  .env.docker
  .github/workflows/.go_unit_test.yml.un~
  .github/workflows/go_unit_test.yml
  .github/workflows/go_unit_test.yml~
  Dockerfile
  cmd/main.go
  pkg/api/routes.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/test/database_test.go
Labels: go

#94 Go API docs
  cmd/main.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  pkg/api/queries.go
  pkg/api/routes.go
Labels: documentation
