Repository TeamStrata/strata, pull requests merged in 2025-07, with the labels that each got.

#129 Fix toasRef typos
  ui/src/components/AdminUsers.vue
  ui/src/components/Charts.vue
  ui/src/components/Queries.vue
  ui/src/components/QueryExecute.vue
Labels: Ready to Merge!, vue

#135 Dash role permissions api
  cmd/main.go
  database/2_data.sql
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  pkg/api/permissions.go
  pkg/database/permissions.go
Labels: go, Ready to Merge!

#141 fix: corrected state sync issue when saving queries
  ui/src/components/Queries.vue
Labels: bug
